// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlpajojjkqbunewzrimo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpscGFqb2pqa3FidW5ld3pyaW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDAyNTQsImV4cCI6MjA2NTQ3NjI1NH0.Opo6adRGO9u8tnAbh0Z4Hio75ktjuqYB7rrdW8ug6Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);